### ISSUE TITLE
Add A Facebook like bar

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencodecollab#101]
Instead Of The Facebook Link In that Navbar.It will be better if we have something like this
![screenshot from 2017-01-23 18-30-15](https://cloud.githubusercontent.com/assets/25057819/22205042/23c7ba0e-e19b-11e6-8527-4c9c7b7fee8a.png)
So That People Will Like The Page Too.
The open code facebook page has only 170 likes.

**Comment by RavicharanN** [comment]
How about this one ?
![screen shot 2017-01-24 at 4 26 32 pm](https://cloud.githubusercontent.com/assets/22046387/22244559/10d45e5e-e252-11e6-903c-2eb351243b55.png)

**Comment by gauthamzz** [comment]
No need of opencode and the O

**Comment by VamsiSangam** [comment]
Will work on this
