### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by adeora7** [fossiiita/opencodecollab#105]
Add a loader in the website.

**Comment by aswinzz** [comment]
i would like to work on it

**Comment by gauthamzz** [comment]
@aswinzz how is this going ?

**Comment by aswinzz** [comment]
still working on it sir

**Comment by aswinzz** [comment]
Completed!
![screenshot from 2017-01-26 05-00-49](https://cloud.githubusercontent.com/assets/25057819/22313801/7ce80a04-e384-11e6-9545-48dd120a1ae4.png)
