### ISSUE TITLE
Show number of commits each person made

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#110]
near the image of the person we would like to show :  how many contributions each person has made.
This issue requires usage of github api.

it should look for all projects in the projects section

**Comment by Anupam-dagar** [comment]
I would like to work on it.

**Comment by Anupam-dagar** [comment]
I would like to work on it.

**Comment by gauthamzz** [comment]
@Anupam-dagar please finish the previous work and once they are merged you can try this .

**Comment by VamsiSangam** [comment]
May I pick up this issue?

**Comment by gauthamzz** [comment]
yeah sure
