### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#116]
The background of the webpage is a bit dull.

please comment here and then start working on this issue.

**Comment by aswanthkoleri** [comment]
i'll work on this

**Comment by aswanthkoleri** [comment]
![screenshot from 2017-01-25 15-47-56](https://cloud.githubusercontent.com/assets/21339090/22286607/bf965cd0-e315-11e6-9f2e-db76cf0bd10f.png)
is this texture background okay

**Comment by gauthamzz** [comment]
Yeah it looks good, but can you try something with a bit more effects

**Comment by gauthamzz** [comment]
solved in #122
