### ISSUE TITLE
make each sections title more appealing

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#123]
the title is very plain now , it would be much preferred if you could make it more appealing :+1: 
something like a nav bar would work

**Comment by agbilotia1998** [comment]
![title](https://cloud.githubusercontent.com/assets/21157929/22373397/b20236ee-e4c7-11e6-808a-724e7da029c9.png)

is it fine sir

**Comment by agbilotia1998** [comment]
![Uploading title.png…]()

**Comment by agbilotia1998** [comment]
![title](https://cloud.githubusercontent.com/assets/21157929/22373814/7d96154a-e4c9-11e6-80d6-8f77e47d4d24.png)

is it fine sir

**Comment by gauthamzz** [comment]
yeah its good , send pr :smile:

**Comment by gauthamzz** [comment]
solved in #145
