### ISSUE TITLE
update readme and add pull request template

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#127]
Update readme as per #125

**Comment by VamsiSangam** [comment]
Working on this

**Comment by gauthamzz** [comment]
could we also have something like a pull request template https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by VamsiSangam** [comment]
Sure sounds great, but I think a separate issue must be made for this.

**Comment by gauthamzz** [comment]
rather just increase the points

**Comment by VamsiSangam** [comment]
I will complete this tomorrow 😄
