### ISSUE TITLE
Change Nav Bar or Header

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#132]
we would like to have a better nav bar, the current one aint upto the mark.
please comment here the nav bar you want to change to then proceed

if you could try a [non rectangular header](https://medium.com/ux-power-tools/tiny-trends-1-non-rectangular-headers-e8d2d4ee578f#.9pte3wnca) it would be nice

**Comment by aswinzz** [comment]
i would like to work on it

**Comment by RavicharanN** [comment]
How 'bout this?
http://codepen.io/jexordexan/pen/zCJBG

**Comment by gauthamzz** [comment]
@RavicharanN no we are looking for something else , and @aswinzz is already working on it
