### ISSUE TITLE
change of order

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#151]
write now the website follows the order 
1. mentors 
2. participants
3. projects
4. issues 

proposed ideas : 
- we can change the order 
1. projects
2. mentors
3. participants 
4. issues 

- We can have separate page for 
1. issues and projects section
2. mentors and students section 

- Stay the way it is 

please comment your opinion :+1:

**Comment by aswinzz** [comment]
we can have separate pages

**Comment by RavicharanN** [comment]
Projects on the top followed by participants and mentors.
Space alloted for the projects and the issue section are very small. So, I don't think making a separate page for them will make it look good.

**Comment by faheemzunjani** [comment]
I think having a separate page for:
- Issues and Projects 
- Mentors and Participants 
will be a better idea with Mentors and Participants page being a part of the landing page.

**Comment by gauthamzz** [comment]
@adeora7 @shubham-padia @mubaris what do you guys say ?

**Comment by shubham-padia** [comment]
Sounds good :)
