### ISSUE TITLE
add gitter chatbox 

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencodecollab#165]
It will be helpful if we add gitter chatbox in the page rather than giving a link in the navbar

**Comment by aswinzz** [comment]
I Am Working On This!

**Comment by Anupam-dagar** [comment]
Can I work on this issue?

**Comment by gauthamzz** [comment]
Ask Aswin . If doesn't reply within a day you can

**Comment by Anupam-dagar** [comment]
@aswinzz can I work on this?

**Comment by aswinzz** [comment]
yeah
