### ISSUE TITLE
Move all relevant code to navbar.html

### ISSUE THREAD

**Issue by VamsiSangam** [fossiiita/opencodecollab#170]
The code for trailer and fb-like button is not fully inside ```navbar.html``` as it is supposed to be. This code is put after the navbar is included which clearly is a part of navbar and must be moved to ```navbar.html```

```
<!-- Main Content -->
<div class="bs-example">
    
    <div id="Trailer" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Trailer of OpenCode</h4>
                </div>
                <div class="video-container">
                    <iframe id="cartoonVideo" width="560" height="315" src="https://www.youtube.com/embed/qkt9vMKYHAM" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
                                                                 
</div>
```
This is the code for fb like button which is put just after the opening of ```body``` tag -

```
<div id="fb-root"></div>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1856478217929449";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
```
this too must also be moved to ```navbar.html```.

All code relevant to the navbar must be put into ```navbar.html``` to avoid duplicating code. Changes made to ```index.html``` must be propagated to ```projects.html``` too.

**Comment by VamsiSangam** [comment]
This is also for #58

**Comment by gauthamzz** [comment]
While doing this issue also add a button at the bottom of 
 mentors and participants page : view projects and issues and vice versa on the other

**Comment by aswinzz** [comment]
i would like to work on it

**Comment by gauthamzz** [comment]
sure

**Comment by aswinzz** [comment]
done

**Comment by gauthamzz** [comment]
@aswinzz @aswanthkoleri @all  please add your score in score.yml
