### ISSUE TITLE
Create a scoreboard

### ISSUE THREAD

**Issue by VamsiSangam** [fossiiita/opencodecollab#171]
We can create a separate page to list out the ranks of all the participants in the event along with their scores and all contributions as gathered in ```scores.yml```. Please display scores in sorted order along with ranks, total score, contributions and participant pic and other info. Any more suggestions regarding the scoreboard are appreciated 😄

**Comment by VamsiSangam** [comment]
@gauthamzz may I work on this issue?

**Comment by gauthamzz** [comment]
Yeah sure :)
