### ISSUE TITLE
Add Close button For gitter chatbox

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencodecollab#191]
there is no close button for gitter chatbox.
this is my contribution to issue number #58

**Comment by Anupam-dagar** [comment]
There is a toggle button for it in navbar

**Comment by aswinzz** [comment]
it would be better if we have a close button because who opens chatbox using that openchat link will not have any idea on how to close the chatbox

**Comment by Anupam-dagar** [comment]
Ok, I would like to fix it.

**Comment by KaustubhShamshery** [comment]
@Anupam-dagar this has been assigned to you

**Comment by gauthamzz** [comment]
progress ?
