### ISSUE TITLE
chat with us option not working when we are using the issues and projects page 

### ISSUE THREAD

**Issue by aswanthkoleri** [fossiiita/opencodecollab#197]
when the chat with us option is clicked  when we are using the page projects and issues it redirects whenever we click on it . please fix the issue

**Comment by aswinzz** [comment]
done

**Comment by aswinzz** [comment]
![screenshot from 2017-02-12 01-01-24](https://cloud.githubusercontent.com/assets/25057819/22856803/07e6804e-f0bf-11e6-9263-0cd39b89cab5.png)
![screenshot from 2017-02-12 01-01-31](https://cloud.githubusercontent.com/assets/25057819/22856804/07f05100-f0bf-11e6-9f64-61088efb3d33.png)
