### ISSUE TITLE
Alignment of contents in scoreboard in mobile view

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencodecollab#214]
The alignment of  contributions in the event scoreboard should be aligned properly in the mobile view
![screenshot_2017-02-13-22-52-00-101](https://cloud.githubusercontent.com/assets/25057819/22894684/ee9c44a2-f23f-11e6-9e66-e7132cd75723.jpeg)

**Comment by agbilotia1998** [comment]
![Uploading mv.png…]()
Is It fine.

**Comment by agbilotia1998** [comment]
![mv](https://cloud.githubusercontent.com/assets/21157929/22932442/f0c0d4a6-f2ed-11e6-8e94-afb61ab9a7b6.png)

Is It fine
