### ISSUE TITLE
fix header.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/opencodecollab#343]
Header on the home page is distorted.

**Comment by gauthamzz** [comment]
you mean its over lapping ,the facebook like part and the github part

**Comment by Anupam-dagar** [comment]
it should be in a single line
opencode is in top and then navigation items start.

**Comment by gauthamzz** [comment]
i dont think this can be done in 10 minutes

**Comment by Anupam-dagar** [comment]
should i count points for creating issue
