### ISSUE TITLE
Make a current issues section on the website using the github api

### ISSUE THREAD

**Issue by shubham-padia** [fossiiita/opencodecollab#41]
Checkout api.github.com for more info.

Requirements:
- live link (gh-pages)
- A social media post or a tweet highlighting the changes you made along with the hashtags " #opencode #geekhaveniiita #iiita "

**Comment by VamsiSangam** [comment]
Planning to implement this below the projects section using jQuery AJAX calls. Is that ok? And what information (title, link to PR, date, etc) am I expected to display? Should I display only the open ones, or all?
