### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#5]
Currently the colloboration site does not have a footer, create a footer along with the necessary links and description.

Requirements:
- Live preview (gh-pages) of your forked repo.
- A social media post or a tweet highlighting the changes you made along with the hashtag " #opencode #geekhaveniiita #iiita "

**Comment by aswanthkoleri** [comment]
In which file shall i include the footer code ??

**Comment by gauthamzz** [comment]
index.html has the footer code

**Comment by aswanthkoleri** [comment]
what are gh-pages ?

**Comment by gauthamzz** [comment]
Go to settings in your fork, you can enable gh pages there ,
see #15

**Comment by Ellusionists** [comment]
![image](https://cloud.githubusercontent.com/assets/21156892/22038354/cef92ea0-dd20-11e6-93cb-58aef269ea47.png)

A very basic footer which servers the purpose.

**Comment by bhanu1911** [comment]
![screenshot from 2017-01-18 22-09-01](https://cloud.githubusercontent.com/assets/19773764/22073224/cc0e9324-ddca-11e6-838a-3b4be4f97daf.png)

A very, very basic, as-yet-unformattted footer; can be edited using CSS for further use.

**Comment by gauthamzz** [comment]
only one of you should work on these kind of errors :+1: we dont want two footers :confounded: . @Ellusionists is working on this , if he doesnt merge within three days you can work on this . right now @bhanu1911 try something else , we have lots of issues

**Comment by gauthamzz** [comment]
Solved in #84
