### ISSUE TITLE
Project link is broken

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#52]
When you click on the image of a particular project is should redirect to the projects respective github link :)

Currently this is broken 

https://github.com/fossiiita/opencodecollab/blob/master/index.html#L187 
should be changed 

Requirements:

- live link (gh-pages)
- A social media post or a tweet highlighting the changes you made along with the hashtags " #opencode #geekhaveniiita #iiita

**Comment by pradeepgangwar** [comment]
I have created a PR check it....

Live session at https://pradeepgangwar.github.io/opencodecollab/

**Comment by gauthamzz** [comment]
solved in #76
