### ISSUE TITLE
Show all infos 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#6]
As you can see in the README.md we are collecting information like github, fb and twitter username of students and mentors . Display all the information in anyway you please , you are welcome to be creative.

Requirements:
- live preview ( gh-pages ) of the changes you made.
- A social media post or a tweet highlighting the changes you made along with the hashtag " #opencode #geekhaveniiita #iiita "

**Comment by VamsiSangam** [comment]
I was thinking of implementing this using materialize's image cards. For that I'll need to replace bootstrap with materialize and rewrite the webpage quite drastically. But the UI will look extremely similar and will display all the info gathered in README. Am I allowed to do such a drastic change in code?

**Comment by gauthamzz** [comment]
Yeah sure:) go for it :)

**Comment by shubham-padia** [comment]
@vamsisangam materialize is a pretty big library, and we are inclined towards keeping bootstrap as it is considered standard. You'll find many pure js examples of showing the info more beautifully that materialize.

**Comment by VamsiSangam** [comment]
Ok sure, I'll try 😄

**Comment by VamsiSangam** [comment]
Last but not the least - [facebook post](https://www.facebook.com/photo.php?fbid=1311044232287968)
