### ISSUE TITLE
Change link format for GitHub username 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossiiita/opencodecollab#70]
Do the changes you mentioned in the flip card pull request. 
@VamsiSangam

**Comment by VamsiSangam** [comment]
Actually I was asked by @shubham-padia in my [PR](https://github.com/fossiiita/opencodecollab/pull/62#issuecomment-273754901) to create a separate issue and a PR for the same.

**Comment by CosmicCoder96** [comment]
Yeah this is the separate issue. Please go ahead.
