### ISSUE TITLE
Make the issue's shown in opencodecollab map to all issues with label opencode

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#81]
We can put all the issues with the tag opencode in this , since we are having multiple project. we want something like [this](https://github.com/search?l=&q=state%3Aopen+label%3Aopencode&ref=advsearch&type=Issues&utf8=%E2%9C%93) 

and remove pull request from that. refer #80 for more detalis

**Comment by VamsiSangam** [comment]
Working on this... Few questions. Upon querying via GitHub API, we [can get too many issues](https://api.github.com/search/issues?q=label:opencode+state:open). So, I don't think we can put all of them using the current UI. I think the UI must be changed to accommodate more issues. Is it ok if I change to UI for this? Next question, all those issues need not belong to Opencode event. I mean, I could create an irrelevant public repo and have issues of label Opencode and it will show up in the query. How do we handle that?

Just letting you know, my previous logic was that I queried for all the issues in a specific repo (opencodecollab), so with my logic you wont get irrelevant issues but it doesn't scale well as new projects are added.

**Comment by gauthamzz** [comment]
firstly reduce the size of issue box and do pagination .

all issues belong to opencode event, i have verified it.
` I could create an irrelevant public repo and have issues of label Opencode and it will show up in the query. How do we handle that?` if something like that occurs we will take care of it. The problem is that the new collaborators wont be knowing what all issues are there. the purpose of this website is to provide a general platform for all projects .

**Comment by VamsiSangam** [comment]
Ok thanks, working on it! 😄

**Comment by gauthamzz** [comment]
Solved , thanks @VamsiSangam
