### ISSUE TITLE
Show General Opencode Info

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#83]
We would like to show all opencode info at the top of this website. Some sort of slider may work. We are open to ideas.

We would like to show opencode poster / opencode trailer there :+1:  You can suggest here then only start working.

**Comment by bhanu1911** [comment]
Sir, please clarify as to what "all opencode info" means, and how you'd like for it to be presented (i.e. some more details about e.g. the "slider".) Also, how much information will it be?

**Comment by gauthamzz** [comment]
@bhanu1911  are you working on this ? please finish all the tasks you are working on

**Comment by gauthamzz** [comment]
No one is currently working on this issue
