### ISSUE TITLE
Fix the mobile view . 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#86]
The github and sidebar are comming on the same side , hence move the side bar right
![screenshot_2017-01-20-22-06-45-795](https://cloud.githubusercontent.com/assets/12110844/22157246/ecf0c59c-df5c-11e6-9f53-79a2ff7120df.jpeg)

**Comment by aswanthkoleri** [comment]
Sir i would like to take up this issue

**Comment by gauthamzz** [comment]
this is already solved
