### ISSUE TITLE
Open graph images

### ISSUE THREAD

**Issue by VamsiSangam** [fossiiita/opencodecollab#88]
So, as all the developers are sharing the website on FB, it is a little awkward to see @shubham-padia 's pic, while sharing the website on FB. Seriously, you are fabulous dude, but I think its better if we serve more event relevant info 😄 

Currently, this is what opencodecollab website looks like when shared -
![capture](https://cloud.githubusercontent.com/assets/11662001/22170138/78bf1996-dfa0-11e6-9b60-8dc5daecad8f.JPG)

We can test it on the [Facebook sharing debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ffossiiita.github.io%2Fopencodecollab%2F). We could add open graph meta tags for site title, description and image to make the shared post look more catchy.

This issue can be seen as my contribution to #58

**Comment by gauthamzz** [comment]
LGTM try it out
