### ISSUE TITLE
Show number of forks and stars 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencodecollab#91]
Show number of forks and stars each project has on the project card , use github api for it

**Comment by VamsiSangam** [comment]
![capture](https://cloud.githubusercontent.com/assets/11662001/22182763/67845c16-e0d3-11e6-8c24-09fe6177b737.JPG)
Isn't it better if we add a flip card to projects where the flipped side would have [github buttons](https://buttons.github.io/) to fork/star the repository directly. This would also show the number of stars/forks as well as it will allow the user to get started with one click. It is simple in terms of code too.

**Comment by gauthamzz** [comment]
Yeah that is what i was also thinking , and what about adding something like :  what language the project is or which platform it uses . i guess we need to make a new field in the projects section as well for that
